action_id: trunk-share-with-everyone
date: 2025-02-25 19:52:22
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1740513142
full_timestamp:
  nanos: 291298000
  seconds: 1740513142
trunk_version: 1.22.10
